### ISSUE TITLE
Library is slow when it's used in bulk

### ISSUE THREAD

**Issue by db1996** [tinohager/Nager.PublicSuffix#31]
I'm using this package on all domains on a DNS server. In my case there are about 3000 domains. It takes about 5 minutes to get the TLD from all of them. Is there any way to speed this up?

**Comment by tinohager** [comment]
Can you show your code?

**Comment by vleeuwenmenno** [comment]
This is still very much a real issue.

Rider Dynamic Program Analysis says the following when I use it on 300 ish domains in bulk
![image](https://user-images.githubusercontent.com/46482143/124114145-7fc6f300-da6c-11eb-8ca9-20d3059211d3.png)

```at TldRuleParser.ParseRules(String)
at WebTldRuleProvider+<BuildAsync>d__5.MoveNext()
at AsyncTaskMethodBuilder+AsyncStateMachineBox<__Canon,WebTldRuleProvider+<BuildAsync>d__5>.ExecutionContextCallback(Object) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 289 column 17
at AsyncTaskMethodBuilder+AsyncStateMachineBox<__Canon,WebTldRuleProvider+<BuildAsync>d__5>.MoveNext(Thread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 327 column 25
at AsyncTaskMethodBuilder+AsyncStateMachineBox<__Canon,WebTldRuleProvider+<BuildAsync>d__5>.MoveNext() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 305 column 39
at FileCacheProvider+<GetAsync>d__4.MoveNext()
at AsyncTaskMethodBuilder+AsyncStateMachineBox<__Canon,FileCacheProvider+<GetAsync>d__4>.ExecutionContextCallback(Object) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 289 column 17
at AsyncTaskMethodBuilder+AsyncStateMachineBox<__Canon,FileCacheProvider+<GetAsync>d__4>.MoveNext(Thread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 327 column 25
at AsyncTaskMethodBuilder+AsyncStateMachineBox<__Canon,FileCacheProvider+<GetAsync>d__4>.MoveNext() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 305 column 39
at AsyncTaskMethodBuilder+AsyncStateMachineBox<Int32,StreamReader+<ReadBufferAsync>d__67>.ExecutionContextCallback(Object) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 289 column 17
```

I only use this lib to get the TLD and when I switch to a simple Split function my page loads WAY faster. But I think supplying this details might help resolving the issue.

I used the following code
```csharp
            List<Dictionary<string, string>> domainList = new List<Dictionary<string, string>>();

            foreach(string domain in domains)
            {
                try
                {
                    Nager.PublicSuffix.DomainInfo info = new DomainParser(new WebTldRuleProvider()).Parse(domain);
                    domainList.Add(new Dictionary<string, string>() {
                        { "name", info.Domain },
                        { "extension", info.TLD }
                    });
                }
                catch (ParseException)
                {
                    return null;
                }
            }

**Comment by tinohager** [comment]
it might be disadvantageous to instantiate the DomainParser in each loop again
